services:
  postgres:
    image: postgres:17.4-alpine
    container_name: app-starter-postgres_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: app-starter
      POSTGRES_PASSWORD: app-starter-password
      POSTGRES_DB: app-starter-db
    volumes:
      - app_starter_postgres_data:/var/lib/postgresql/data

volumes:
  app_starter_postgres_data:
